[package]
name = "parseline"
version = "0.1.0"
authors = ["albheim@hotmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coverage = []

[dependencies]